### PR TITLE
make buildx fast again when yum update

### PR DESCRIPTION
**Pull request by pounard**
Since a few month, `yum upgrade` is so slow I was never able to let it finish any build.

I found some trails on this topic here https://stackoverflow.com/questions/73185002/yum-update-stucks-inside-docker and here https://github.com/docker/buildx/issues/379 it seems to be a CentOS related problem.

Using `ulimit` fixes the problem.

### CODE REVIEW

**Comment by polarathene** [comment]
You're setting both soft and hard limit to `1024000`, which is [not what I'd advise](https://github.com/docker/buildx/issues/379#issuecomment-1475116812).

- Soft limit should be `ulimit -Sn 1024`, some software is not compatible with that being higher for legacy reasons, software that needs higher should output an error / failure about needing more file descriptors, and those processes can individually raise their soft limit, you shouldn't set it higher for all as a default.
- Hard limit should be `ulimit -Hn 524288`, which is the modern default if not changed (docker service file does) unless you have systemd release `< 240`. The maximum prior to that was via `sysctl fs.nr_open` which would have been `1048576` (aka `2^20`).

Usually the limit problem is due to the soft limit being too high (_presently docker service files `LimitNOFILE=infinity` equates to `2^20` or `2^30`_), which sets both soft and hard limit to these values of over a million or billion. You want `1024` soft, `524288` hard.

**Comment by pounard** [comment]
@polarathene that's only soft-setting it during yum commands during build session, not in the final container itsef.

**Comment by polarathene** [comment]
You should still be using a soft limit of 1024 AFAIK.

```bash
ulimit -Sn 1024 && ulimit -Hn 524288
```

**Comment by pounard** [comment]
Thanks for the tips, I'll let the maintainer decide of that thought

**Pull request closed without merging**
